

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PaymentExampleApp.Model
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class PaymentsEntities : DbContext
{
    public PaymentsEntities()
        : base("name=PaymentsEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<category> category { get; set; }

    public virtual DbSet<Pay> Pay { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

    public virtual DbSet<Users> Users { get; set; }

}

}

