
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PaymentExampleApp.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Pay
{

    public int id { get; set; }

    public Nullable<System.DateTime> Date_payment { get; set; }

    public Nullable<int> Category_id { get; set; }

    public Nullable<int> User_id { get; set; }

    public string Name { get; set; }

    public Nullable<int> Count { get; set; }

    public Nullable<double> Price { get; set; }

    public Nullable<double> Cost { get; set; }



    public virtual category category { get; set; }

    public virtual Users Users { get; set; }

}

}
